### ISSUE TITLE
Plugin does not work on Yatopia core 

### ISSUE THREAD

**Issue by Kurasava** [plasmoapp/plasmo-voice#14]
I have installed the latest version of the plugin on a server with Iatopia core. When you enter for 5 seconds, everything works, then an icon of connection problems appears, and after 15 seconds this icon also tries. In this case, above the player there is an icon of no installed mod, although the mod is installed

**Comment by KPidS** [comment]
Check if you have the port open. And also try to enter the IP address of your server in the config: 
```yml
udp:
# Enter the IP address of your server here 
  ip: 0.0.0.0
  port: 60606
```
Be aware that you need to have the UDP port open. Ask your hosting provider if they have UDP ports open.
