### ISSUE TITLE
Make hear distance larger

### ISSUE THREAD

**Issue by yRipper** [plasmoapp/plasmo-voice#8]
is there any way i could make it a longer distance?? by editing the mod or the server plugin?? or it has to be both?

**Comment by KPidS** [comment]
Each player can change distance with a slider in the settings. 

![image](https://user-images.githubusercontent.com/27863947/114398571-9b76d780-9ba8-11eb-9909-64240736fdd5.png)

You can also configure distance presets in the plugin config. 

```yml
# Voice distance
distances:
  - 8
  - 16
  - 24
# Default voice distance
# If 0 distance will be first element from distances
default_distance: 16
```

There is also `voice.priority` permission which allows you to bind a separate push to talk for talking in a higher radius which you can set with the `/vc priority-distance <number>` command.
